INSERT INTO amenities (name, icon) VALUES
  ('WiFi',             'wifi'),
  ('Parking',          'car'),
  ('Air Conditioning', 'snowflake'),
  ('Pool',             'waves'),
  ('Kitchen',          'utensils'),
  ('Washing Machine',  'washing-machine'),
  ('TV',               'tv'),
  ('Pet Friendly',     'paw-print'),
  ('Grill',            'flame'),
  ('Balcony',          'building'),
  ('Spa',              'spa'),
  ('Gym',              'gym'),
  ('Room Service',     'room-service'),
  ('Sea View',         'sea-view'),
  ('Mountain View',    'mountain-view'),
  ('Kettle',           'kettle'),
  ('Breakfast',        'breakfast'),
  ('Lunch',            'lunch'),
  ('Dinner',           'dinner')
ON CONFLICT (icon) DO NOTHING;
